import type { Alumni } from "@/types/alumni"

export const sampleAlumni: Alumni[] = [
  {
    id: "1",
    name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    mobile: "+91 9876543210",
    graduationYear: 2018,
    department: "cse",
    jobTitle: "Senior Software Engineer",
    company: "Microsoft",
    linkedinUrl: "https://linkedin.com/in/rahulsharma",
    location: "Bangalore, India",
    bio: "Working on cloud infrastructure and distributed systems at Microsoft. Previously at Amazon. Specialized in building scalable backend services and distributed systems.",
    profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&q=80",
  },
  // {
  //   id: "2",
  //   name: "Priya Patel",
  //   email: "priya.patel@example.com",
  //   mobile: "+91 9876543211",
  //   graduationYear: 2019,
  //   department: "ece",
  //   jobTitle: "Hardware Design Engineer",
  //   company: "Intel",
  //   linkedinUrl: "https://linkedin.com/in/priyapatel",
  //   location: "Pune, India",
  //   bio: "Specializing in VLSI design and verification. Passionate about semiconductor technology and hardware acceleration for AI applications.",
  //   profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop&q=80",
  // },
  {
    id: "2",
    name: "Priya Patel",
    email: "priya.patel@example.com",
    mobile: "+91 9876543211",
    graduationYear: 2019,
    department: "ece",
    jobTitle: "Hardware Design Engineer",
    company: "Intel",
    linkedinUrl: "https://linkedin.com/in/priyapatel",
    location: "Pune, India",
    bio: "Specializing in VLSI design and verification. Passionate about semiconductor technology and hardware acceleration for AI applications.",
    profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "3",
    name: "Amit Kumar",
    email: "amit.kumar@example.com",
    mobile: "+91 9876543212",
    graduationYear: 2015,
    department: "me",
    jobTitle: "Product Manager",
    company: "Tata Motors",
    linkedinUrl: "https://linkedin.com/in/amitkumar",
    location: "Mumbai, India",
    bio: "Leading product development for electric vehicles. MBA from IIM Ahmedabad. Passionate about sustainable transportation solutions and green technology.",
    profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "4",
    name: "Neha Gupta",
    email: "neha.gupta@example.com",
    mobile: "+91 9876543213",
    graduationYear: 2020,
    department: "it",
    jobTitle: "Data Scientist",
    company: "Amazon",
    linkedinUrl: "https://linkedin.com/in/nehagupta",
    location: "Hyderabad, India",
    bio: "Working on machine learning models for product recommendations. MS in Data Science from IIT Delhi. Experienced in natural language processing and computer vision.",
    profileImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "5",
    name: "Vikram Singh",
    email: "vikram.singh@example.com",
    mobile: "+91 9876543214",
    graduationYear: 2017,
    department: "ce",
    jobTitle: "Project Manager",
    company: "L&T Construction",
    linkedinUrl: "https://linkedin.com/in/vikramsingh",
    location: "Delhi, India",
    bio: "Managing infrastructure projects across North India. PMP certified professional with expertise in large-scale construction management and sustainable building practices.",
    profileImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "6",
    name: "Ananya Desai",
    email: "ananya.desai@example.com",
    mobile: "+91 9876543215",
    graduationYear: 2016,
    department: "cse",
    jobTitle: "Tech Lead",
    company: "Google",
    linkedinUrl: "https://linkedin.com/in/ananyad",
    location: "Bangalore, India",
    bio: "Working on Google Search infrastructure. Previously at Oracle and IBM. Specialized in distributed systems and high-performance computing architectures.",
    profileImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "7",
    name: "Rajesh Verma",
    email: "rajesh.verma@example.com",
    mobile: "+91 9876543216",
    graduationYear: 2014,
    department: "ee",
    jobTitle: "Senior Electrical Engineer",
    company: "BHEL",
    linkedinUrl: "https://linkedin.com/in/rajeshverma",
    location: "Bhopal, India",
    bio: "Specializing in power systems and renewable energy solutions. Working on smart grid technologies and energy management systems for industrial applications.",
    profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "8",
    name: "Meera Joshi",
    email: "meera.joshi@example.com",
    mobile: "+91 9876543217",
    graduationYear: 2021,
    department: "bt",
    jobTitle: "Research Scientist",
    company: "Biocon",
    linkedinUrl: "https://linkedin.com/in/meerajoshi",
    location: "Pune, India",
    bio: "Working on vaccine development and immunology research. PhD in Biotechnology with focus on molecular biology and genetic engineering techniques.",
    profileImage: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "9",
    name: "Sanjay Mehta",
    email: "sanjay.mehta@example.com",
    mobile: "+91 9876543218",
    graduationYear: 2013,
    department: "che",
    jobTitle: "Process Engineer",
    company: "Reliance Industries",
    linkedinUrl: "https://linkedin.com/in/sanjaymehta",
    location: "Mumbai, India",
    bio: "Optimizing petrochemical processes and implementing sustainable practices. Expert in process optimization and environmental compliance in the chemical industry.",
    profileImage: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "10",
    name: "Aditya Kapoor",
    email: "aditya.kapoor@example.com",
    mobile: "+91 9876543219",
    graduationYear: 2022,
    department: "csbs",
    jobTitle: "Business Analyst",
    company: "Deloitte",
    linkedinUrl: "https://linkedin.com/in/adityakapoor",
    location: "Gurgaon, India",
    bio: "Helping businesses leverage data for strategic decision making. Specialized in financial analytics and business intelligence solutions for banking and fintech clients.",
    profileImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "11",
    name: "Kavita Reddy",
    email: "kavita.reddy@example.com",
    mobile: "+91 9876543220",
    graduationYear: 2017,
    department: "aiml",
    jobTitle: "AI Research Engineer",
    company: "NVIDIA",
    linkedinUrl: "https://linkedin.com/in/kavitareddy",
    location: "Bangalore, India",
    bio: "Developing next-generation deep learning models for computer vision applications. Published researcher in the field of generative adversarial networks and their applications.",
    profileImage: "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "12",
    name: "Arjun Nair",
    email: "arjun.nair@example.com",
    mobile: "+91 9876543221",
    graduationYear: 2019,
    department: "cse-ds",
    jobTitle: "Data Engineer",
    company: "Flipkart",
    linkedinUrl: "https://linkedin.com/in/arjunnair",
    location: "Bangalore, India",
    bio: "Building scalable data pipelines and analytics infrastructure. Experienced in big data technologies and cloud-native architectures for e-commerce platforms.",
    profileImage: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "13",
    name: "Ritu Sharma",
    email: "ritu.sharma@example.com",
    mobile: "+91 9876543222",
    graduationYear: 2020,
    department: "cybersecurity",
    jobTitle: "Security Consultant",
    company: "EY",
    linkedinUrl: "https://linkedin.com/in/ritusharma",
    location: "Delhi, India",
    bio: "Helping organizations strengthen their security posture through penetration testing and security assessments. Certified ethical hacker with expertise in network and application security.",
    profileImage: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "14",
    name: "Karan Malhotra",
    email: "karan.malhotra@example.com",
    mobile: "+91 9876543223",
    graduationYear: 2018,
    department: "iota",
    jobTitle: "IoT Solutions Architect",
    company: "Siemens",
    linkedinUrl: "https://linkedin.com/in/karanmalhotra",
    location: "Pune, India",
    bio: "Designing and implementing IoT solutions for industrial automation. Specialized in edge computing and industrial IoT platforms for manufacturing and energy sectors.",
    profileImage: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "15",
    name: "Divya Krishnan",
    email: "divya.krishnan@example.com",
    mobile: "+91 9876543224",
    graduationYear: 2016,
    department: "cse",
    jobTitle: "Engineering Manager",
    company: "Adobe",
    linkedinUrl: "https://linkedin.com/in/divyakrishnan",
    location: "Noida, India",
    bio: "Leading engineering teams building creative cloud applications. Passionate about building high-performance teams and mentoring junior engineers in their career growth.",
    profileImage: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "16",
    name: "Rohit Choudhary",
    email: "rohit.choudhary@example.com",
    mobile: "+91 9876543225",
    graduationYear: 2015,
    department: "me",
    jobTitle: "Automotive Design Engineer",
    company: "Mahindra & Mahindra",
    linkedinUrl: "https://linkedin.com/in/rohitchoudhary",
    location: "Chennai, India",
    bio: "Designing next-generation electric vehicles with focus on aerodynamics and energy efficiency. Experienced in computational fluid dynamics and structural analysis.",
    profileImage: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "17",
    name: "Sneha Agarwal",
    email: "sneha.agarwal@example.com",
    mobile: "+91 9876543226",
    graduationYear: 2021,
    department: "csbs",
    jobTitle: "Management Consultant",
    company: "McKinsey & Company",
    linkedinUrl: "https://linkedin.com/in/snehaagarwal",
    location: "Mumbai, India",
    bio: "Advising Fortune 500 companies on digital transformation strategies. MBA from ISB with focus on technology management and business analytics.",
    profileImage: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "18",
    name: "Varun Menon",
    email: "varun.menon@example.com",
    mobile: "+91 9876543227",
    graduationYear: 2014,
    department: "ece",
    jobTitle: "VLSI Design Engineer",
    company: "Texas Instruments",
    linkedinUrl: "https://linkedin.com/in/varunmenon",
    location: "Bangalore, India",
    bio: "Designing analog and mixed-signal integrated circuits for automotive applications. Specialized in low-power design techniques and signal processing circuits.",
    profileImage: "https://images.unsplash.com/photo-1508341591423-4347099e1f19?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "19",
    name: "Anjali Deshmukh",
    email: "anjali.deshmukh@example.com",
    mobile: "+91 9876543228",
    graduationYear: 2019,
    department: "it",
    jobTitle: "UX Designer",
    company: "Wipro",
    linkedinUrl: "https://linkedin.com/in/anjalideshmukh",
    location: "Hyderabad, India",
    bio: "Creating intuitive and accessible user experiences for enterprise applications. Passionate about human-centered design and inclusive design practices.",
    profileImage: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "20",
    name: "Nikhil Tandon",
    email: "nikhil.tandon@example.com",
    mobile: "+91 9876543229",
    graduationYear: 2022,
    department: "aiml",
    jobTitle: "Machine Learning Engineer",
    company: "Swiggy",
    linkedinUrl: "https://linkedin.com/in/nikhiltandon",
    location: "Bangalore, India",
    bio: "Building recommendation systems and demand forecasting models for food delivery platform. Specialized in reinforcement learning and time-series analysis.",
    profileImage: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=300&h=300&fit=crop&q=80",
  },
  {
    id: "20",
    name: "Sudarshan patil",
    email: "nikhil.tandon@example.com",
    mobile: "+91 9876543229",
    graduationYear: 2022,
    department: "aiml",
    jobTitle: "Machine Learning Engineer",
    company: "Swiggy",
    linkedinUrl: "https://linkedin.com/in/nikhiltandon",
    location: "Bangalore, India",
    bio: "Building recommendation systems and demand forecasting models for food delivery platform. Specialized in reinforcement learning and time-series analysis.",
    profileImage: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=300&h=300&fit=crop&q=80",
  }
]
